name: Android CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permissions
      run: chmod +x gradlew build.sh build-splice.sh

    - name: Run Official Build Script
      run: |
        export ANDROID_NDK=$ANDROID_NDK_LATEST_HOME
        ./build.sh

    - name: Upload DFReroot App APK
      uses: actions/upload-artifact@v4
      with:
        name: Samsung_Root_App
        path: df_reroot.apk

    - name: Upload DFInstaller APK
      uses: actions/upload-artifact@v4
      with:
        name: DFInstaller
        path: df_installer.apk
